alias pac='$ACCESS pacman'
alias t='trizen'
alias p='pac'
alias :v='t'
alias fix='srm /var/lib/pacman/db.lck'
alias rmp='p -Rcnsuv'
alias vcp='$ACCESS downgrade'
alias rmpac='pacman -Rcnsu $(pacman -Qsqq | fzf -m 10000)'
